[package]
name = "sincere"
version = "0.2.1"
authors = ["dangcheng <dangcheng@hotmail.com>"]

[dependencies]
soio = { git="https://github.com/mcorce/soio.git" }
threading = "0.1"
chrono = "0.3"
regex = "0.2"
rustls = "0.5"
