[package]
name          = "sincere"
version       = "0.2.8"
license       = "MIT"
authors       = ["dangcheng <dangcheng@hotmail.com>"]
description   = "web framework"
documentation = "https://docs.rs/sincere"
homepage      = "https://github.com/mcorce/sincere"
repository    = "https://github.com/mcorce/sincere"
readme        = "README.md"
keywords      = ["web", "api"]
exclude       = [
  ".gitignore",
  ".travis.yml",
  "deploy.sh",
  "test/**/*",
]

[dependencies]
soio = "0.2"
chrono = "0.3"
regex = "0.2"
rustls = "0.9"
serde = "1.0"
serde_json = "1.0"
serde_urlencoded = "0.5"
