[package]
name          = "sincere"
version       = "0.4.0"
license       = "MIT"
authors       = ["mitum <dangcheng@hotmail.com>"]
description   = "web framework"
documentation = "https://docs.rs/sincere"
homepage      = "https://github.com/mitum/sincere"
repository    = "https://github.com/mitum/sincere"
readme        = "README.md"
keywords      = ["web", "api"]
exclude       = [
  ".gitignore",
  ".travis.yml",
  "deploy.sh",
  "test/**/*",
]

[dependencies]
queen = "0.1"
chrono = "0.4"
regex = "0.2"
rustls = "0.11"
serde = "1.0"
serde_json = "1.0"
url = "1.6"
httparse = "1.2"
num_cpus = "1.7"
