[package]
name          = "sincere"
version       = "0.3.13"
license       = "MIT"
authors       = ["mitum <dangcheng@hotmail.com>"]
description   = "web framework"
documentation = "https://docs.rs/sincere"
homepage      = "https://github.com/mitum/sincere"
repository    = "https://github.com/mitum/sincere"
readme        = "README.md"
keywords      = ["web", "api"]
exclude       = [
  ".gitignore",
  ".travis.yml",
  "deploy.sh",
  "test/**/*",
]

[dependencies]
soio = "0.2"
queen = "0.1"
chrono = "0.4"
regex = "0.2"
rustls = "0.11"
serde = "1.0"
serde_json = "1.0"
url = "1.5"
httparse = "1.2"
num_cpus = "1.7"

tokio-core = "0.1"
tokio-io = "0.1"
tokio-proto = "0.1"
tokio-service = "0.1"
bytes = { version = "0.4", features = ["serde"] }
futures = "0.1"
futures-cpupool = "0.1"
