[package]
name = "sincere"
version = "0.1.0"
authors = ["dangcheng <dangcheng@hotmail.com>"]

[dependencies]
soio = { path = "../soio" }
threading = { path = "../threading" }
chrono = "0.2"
regex = "0.2"
