[package]
name          = "sincere"
version       = "0.5.0"
license       = "MIT"
authors       = ["mitum <dangcheng@hotmail.com>"]
description   = "web framework"
documentation = "https://docs.rs/sincere"
homepage      = "https://github.com/mitum/sincere"
repository    = "https://github.com/mitum/sincere"
readme        = "README.md"
keywords      = ["web", "api"]
exclude       = [
  ".gitignore",
  ".travis.yml",
  "deploy.sh",
  "test/**/*",
]

[dependencies]
queen-io = "0.1"
chrono = "0.4"
regex = "0.2"
serde = "1.0"
serde_json = "1.0"
url = "1.6"
httparse = "1.2"
num_cpus = "1.7"
libc = "0.2"
mime = "0.3"

buf_redux = "0.6"
twoway = "0.1"
tempdir = "0.3.6"
rand = "0.4.2"
